  [[redirects]]
  from = "https://use-shopping-cart.netlify.app"
  to = "https://useshoppingcart.com"
  status = 301

  [[redirects]]
  from = "https://use-shopping-cart.netlify.app/*"
  to = "https://useshoppingcart.com/:splat"
  status = 301
